config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    resources :products, only:[:show,:index,:create]

    root 'welcome#index'
    devise_for :users , controllers: {sessions: "sessions"}

  #    namespace :shopping do
  #     resources :cart_items
  # end
    
	 resource :cart, only: [:show] do
	  put 'add/:product_id', to: 'carts#add', as: :add_to
	  put 'remove/:product_id', to: 'carts#remove', as: :remove_from
	end
  
  get '/wishlists' => "wishlists#index"
  post '/wishlists' => "wishlists#create"
  delete '/wishlists/:id' => "wishlists#destroy"

end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :product_type
	belongs_to :prototype
	belongs_to :brand
  belongs_to :wishlist

	has_many :product_properties

	has_many :properties, through: :product_properties

  has_many :variants
  has_many :images, -> {order(:position)},
                    as:        :imageable,
                    dependent: :destroy

  has_many :active_variants, -> { where(deleted_at: nil) },
    class_name: 'Variant'

  accepts_nested_attributes_for :variants,           reject_if: proc { |attributes| attributes['sku'].blank? }
  accepts_nested_attributes_for :product_properties, reject_if: proc { |attributes| attributes['description'].blank? }, allow_destroy: true
  accepts_nested_attributes_for :images,             reject_if: proc { |t| (t['photo'].nil? && t['photo_from_link'].blank? && t['id'].blank?) }, allow_destroy: true

  # validates :product_type_id, presence: true
  # validates :name, presence: true

  # validate :ensure_available


 def self.featured
 	product = where({ products: { featured: true} }).includes(:images)
 	product ? product : includes(:images).where(['products.deleted_at IS NULL'])
 end

  def active(at = Time.zone.now)
    deleted_at.nil? || deleted_at > (at + 1.second)
  end

  def active?(at = Time.zone.now)
    active(at)
  end

  def activate!
    self.deleted_at = nil
    save
  end

 def self.active
    where({products: {active: true}}).includes(:images)
 end
 
  def featured_image(image_size = :small)
  Rails.cache.fetch("Product-featured_image-#{id}-#{image_size}") do
    images.first ? images.first.photo.url(image_size) : "no_image_#{image_size.to_s}.jpg"
  end
  end
  def featured_image1(image_size = :large)
  Rails.cache.fetch("Product-featured_image-#{id}-#{image_size}") do
    images.first ? images.first.photo.url(image_size) : "no_image_#{image_size.to_s}.jpg"
  end
  end
  def image_urls(image_size = :small)
    Rails.cache.fetch("Product-image_urls-#{id}-#{image_size}") do
      images.empty? ? ["no_image_#{image_size.to_s}.jpg"] : images.map{|i| i.photo.url(image_size) }
    end
  end

  def cart_action(current_user_id)
    if $redis.sismember "cart#{current_user_id}", id
      "Remove from"
    else
      "Add to"
    end
  end

private

    def has_active_variants?
      active_variants.any?{|v| v.is_available? }
    end

    # def ensure_available
    #   if active? && deleted_at_changed?
    #     self.errors.add(:base, 'There must be active variants.')  if active_variants.blank?
    #     self.errors.add(:base, 'Variants must have inventory.')   unless active_variants.any?{|v| v.is_available? }
    #     self.deleted_at = deleted_at_was if active_variants.blank? || !active_variants.any?{|v| v.is_available? }
    #   end
    # end
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
  has_many :products, dependent: :restrict_with_exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	products = Product.active.includes(:variants)
  	product_types = nil
  	if params[:product_type_id].present? && product_type = ProductType.find_by_id(params[:product_type_id])
  		product_types = product_type.self_and_descendants.map(&:id)
  	end
  	if product_types
  		@products = products.where(product_type_id: product_types)
  	else
  		@products = products
  	end

  end

  def show
  	@products = Product.all
    @product = Product.find(params[:id])
    @cart_action = @product.cart_action current_user.try :id
  end

  def create

  end
  
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<section id="advertisement">
		<div class="container">
			<img src="images/shop/advertisement.jpg" alt="" />
		</div>
</section>
	<section>
		<div class="container">
			<div class="row">
				<%#= render "shared/filter" %>
				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">Features Items</h2>
						<% @products.each_with_index do |product,i|%>
							<div class="col-sm-4">
								<div class="product-image-wrapper">
									<div class="single-products">
										<div class="productinfo text-center">
											 <%= link_to image_tag(product.featured_image(:medium)), product_path(product), title: product.name, class:  'clearfix' %>
											<h2>$56</h2>
											<p><%= link_to product.name,product_path(product) %></p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
										<div class="product-overlay">
											<div class="overlay-content">
												<h2>$56</h2>
												<p><%= product.name%></p>
												<!-- <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a> -->
												<p><%= link_to product.name,product_path(product)%></p>
												<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>

											</div>
										</div>
									</div>
									<div class="choose">
										<ul class="nav nav-pills nav-justified">
											<li> <%= link_to "Add to Wishlist", wishlists_path, :class => "fa fa-plus-square" %>
											</li>
											<li><a href=""><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
											<li><a href=""><i class="fa fa-plus-square"></i>Add to compare</a></li>
										</ul>
									</div>
								</div>
							</div>
						<%end%>
						<ul class="pagination">
							<li class="active"><a href="">1</a></li>
							<li><a href="">2</a></li>
							<li><a href="">3</a></li>
							<li><a href="">&raquo;</a></li>
						</ul>
					</div><!--features_items-->
				</div>
			</div>
		</div>
	</section>

app/views/products/show.html.erb
	<section>
		<div class="container">
			<div class="row">
				<%= render "shared/filter" %>
				
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<%= image_tag @product.featured_image(:large)%>
<!-- 								<h3>ZOOM</h3> -->
							</div>
<!-- 							<div id="similar-product" class="carousel slide" data-ride="carousel">
								 -->
								  <!-- Wrapper for slides -->
<!-- 								    <div class="carousel-inner">
										<div class="item active">
										  <a href=""><%#= image_tag @product.images.first.photo.url(:small)%></a>
										</div>
										<div class="item">
										  <a href=""><%#= image_tag @product.images.second.photo.url(:small)%></a>
										</div>
										<div class="item">
										  <a href=""><%#= image_tag @product.images.third.photo.url(:small)%></a>
										</div>
										
									</div> -->

								  <!-- Controls -->
<!-- 								  <a class="left item-control" href="#similar-product" data-slide="prev">
									<i class="fa fa-angle-left"></i>
								  </a>
								  <a class="right item-control" href="#similar-product" data-slide="next">
									<i class="fa fa-angle-right"></i>
								  </a>
							</div> -->

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<img src="/assets/product-details/new.jpg" class="newarrival" alt="" />
								<h2><%= @product.name%></h2>
								<img src="/assets/product-details/rating.png" alt="" />
								<span>
									<span>US $59</span>
									<label>Quantity:</label>
									<input type="text" value="3" />

								</span><br>
								<%if signed_in?%>
									  <%=link_to "", class: "btn btn-fefault cart", data: {target: @cart_action, addUrl: add_to_cart_path(@product), removeUrl: remove_from_cart_path(@product)} do%>
									    <i class="fa fa-shopping-cart"></i>
									    <span><%=@cart_action%></span> Cart
									  <%end%>
									<%end%>
								<p><b>Availability:</b> In Stock</p>
								<p><b>Condition:</b> New</p>
								<p><b>Brand:</b> E-SHOPPER</p>
								<a href=""><img src="/assets/product-details/share.png" class="share img-responsive"  alt="" /></a>
							</div><!--/product-information-->
						</div>
					</div><!--/product-details-->				
				</div>
			</div>
		</div>
	</section>