config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    resources :products, only:[:show,:index,:create]

    root 'welcome#index'
    devise_for :users , controllers: {sessions: "sessions"}

  #    namespace :shopping do
  #     resources :cart_items
  # end
    
	 resource :cart, only: [:show] do
	  put 'add/:product_id', to: 'carts#add', as: :add_to
	  put 'remove/:product_id', to: 'carts#remove', as: :remove_from
	end
  
  get '/wishlists' => "wishlists#index"
  post '/wishlists' => "wishlists#create"
  delete '/wishlists/:id' => "wishlists#destroy"

end

app/views/layouts/_footer.html.erb
<footer id="footer"><!--Footer-->
		
		<div class="footer-widget">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Service</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Online Help</a></li>
								<li><a href="#">Contact Us</a></li>
								<li><a href="#">Order Status</a></li>
								<li><a href="#">Change Location</a></li>
								<li><a href="#">FAQ’s</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Quock Shop</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">T-Shirt</a></li>
								<li><a href="#">Mens</a></li>
								<li><a href="#">Womens</a></li>
								<li><a href="#">Gift Cards</a></li>
								<li><a href="#">Shoes</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Policies</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Terms of Use</a></li>
								<li><a href="#">Privecy Policy</a></li>
								<li><a href="#">Refund Policy</a></li>
								<li><a href="#">Billing System</a></li>
								<li><a href="#">Ticket System</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Company Information</a></li>
								<li><a href="#">Careers</a></li>
								<li><a href="#">Store Location</a></li>
								<li><a href="#">Affillate Program</a></li>
								<li><a href="#">Copyright</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3 col-sm-offset-1">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<form action="#" class="searchform">
								<input type="text" placeholder="Your email address" />
								<button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
								<p>Get the most recent updates from <br />our site and be updated your self...</p>
							</form>
						</div>
					</div>
					
				</div>
			</div>
		</div>
		
		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
					<p class="pull-right">Designed by <span><a target="_blank" href="http://www.themeum.com">Themeum</a></span></p>
				</div>
			</div>
		</div>
		
	</footer><!--/Footer-->
	

app/views/layouts/_headerBottom.html.erb
<div class="header-bottom"><!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li><%= link_to "Home", root_path, :class => "active" %></li>

								<li class="dropdown"><%= link_to 'Shop<i class="fa fa-angle-down"></i>'.html_safe, products_path %>
                                    <ul role="menu" class="sub-menu">
                                        <li><%= link_to "Products",products_path%></li>
										<li><%= link_to "Login",new_user_session_path%></li> 
                                    </ul>
                                </li> 
							</ul>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="search_box pull-right">
							<input type="text" placeholder="Search"/>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-bottom-->

app/views/layouts/_headerMiddle.html.erb
		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="logo pull-left">
							<a href="index.html"><img src="/assets/logo.png" alt="" /></a>
						</div>
					</div>
					<div class="col-sm-8">
						<div class="shop-menu pull-right">
							<ul class="nav navbar-nav">
<!-- 								<li><a href="#"><i class="fa fa-star"></i> Wishlist</a></li>
								<li><a href="checkout.html"><i class="fa fa-crosshairs"></i> Checkout</a></li> -->

								<%if current_user.present? %>
								<li><%= link_to wishlists_path do%>
								    <i class="fa fa-star"></i>
								    Wishlist
								  <%end%></li>
								<li>
								  <%= link_to cart_path do%>
								    <i class="fi-shopping-cart"></i>
								    My Cart
									(<span class="cart-count"><%=current_user.cart_count%></span>)
								  <%end%>
								</li>
								<li><%= link_to current_user.email, edit_user_registration_path %></li>
								<li><%= link_to 'Logout', destroy_user_session_path, method: :delete %>
								<%else%>
									<li><%= link_to '<i class="fa fa-lock"></i> Login'.html_safe, new_user_session_path %></li>
								<%end%>
							</ul> 
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-middle-->

app/views/layouts/_headerTop.html.erb
	<header id="header"><!--header-->
		<div class="header_top"><!--header_top-->
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<div class="contactinfo">
							<ul class="nav nav-pills">
								<li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
								<li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="social-icons pull-right">
							<ul class="nav navbar-nav">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header_top-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecomm</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
 
  <%= csrf_meta_tags %>

</head>
<body>
<header>
	<%#= render 'layouts/headerTop' %>
	<%= render 'layouts/headerMiddle' %>
	<%= render 'layouts/headerBottom' %>
</header>

<%= yield %>
	<%= render 'layouts/footer' %>

   <%= javascript_include_tag "application"%>
</body>
</html>